name: skawa_components_example
version: 1.2.0

environment:
  sdk: '>=2.4.0'

dependencies:
  angular: ^6.0.0-alpha
  angular_components: ^0.14.0-alpha
  skawa_components: ^1.2.0
  skawa_material_components: ^1.2.0
  sass_builder: ^2.1.2
dev_dependencies:
  build_runner: ^1.3.2
  build_web_compilers: ^2.0.0
  build_config: ^0.3.1+4