name: skawa_components_example
version: 1.0.0-beta

environment:
  sdk: '>=2.1.0'

dependencies:
  angular: ^5.2.0
  angular_components: ^0.10.1
  skawa_components:
    git:
      url: https://github.com/skawa-universe/skawa_components.git
      ref: da2-upgrade
      path: skawa_components
  skawa_material_components:
    git:
      url: https://github.com/skawa-universe/skawa_components.git
      ref: da2-upgrade
      path: skawa_material_components
dev_dependencies:
  build_runner: ^1.1.2
  build_web_compilers: ^1.0.0