name: skawa_components_example
version: 1.0.0-beta

environment:
  sdk: '>=2.0.0-dev.51.0 <2.0.0'

dependencies:
  angular: ^5.0.0-alpha
  angular_components: 0.9.0-alpha+11
  angular_router: 2.0.0-alpha+11
  skawa_components:
    path: ../../skawa_components/skawa_components
  skawa_material_components:
    path: ../../skawa_components/skawa_material_components
#    git:
#      url: https://github.com/skawa-universe/skawa_components.git
#      ref: 1.0.0-alpha+1
dev_dependencies:
  build_runner: ^0.8.8
  build_test: ^0.10.0
  build_web_compilers: ^0.4.0