name: skawa_components_example
version: 1.0.0

environment:
  sdk: '>=2.1.0'

dependencies:
  angular: ^5.2.0
  angular_components: ^0.11.0
  skawa_components: ^1.0.0
  skawa_material_components: ^1.0.0
dev_dependencies:
  build_runner: ^1.1.2
  build_web_compilers: ^1.0.0