name: skawa_components_example
version: 1.1.0

environment:
  sdk: '>=2.3.0'

dependencies:
  angular: ^5.3.0
  angular_components: ^0.13.0
  skawa_components: ^1.0.0+4
  skawa_material_components: ^1.0.0+4
  sass_builder: ^2.1.2
dev_dependencies:
  build_runner: ^1.3.2
  build_web_compilers: ^2.0.0
  build_config: ^0.3.1+4