name: skawa_components_example
version: 0.0.2

dependencies:
  angular2: ^3.1.0
  angular_components: ^0.5.1
  skawa_components:
    git:
      url: https://github.com/skawa-universe/skawa_components.git
      ref: 0.0.5
  browser:
dev_dependencies:
  sass_builder: ^0.1.0
transformers:
- angular2:
    entry_points: web/main.dart
