name: skawa_components_example
version: 0.0.1

dependencies:
  angular2: ^3.1.0
  angular_components: ^0.5.1
  skawa_components:
    git: https://github.com/skawa-universe/skawa_components.git


dev_dependencies:
  sass_builder: ^0.1.0
  dart_to_js_script_rewriter:
  browser:

transformers:
- angular2:
    entry_points:
    - web/main.dart
    platform_directives:
    - 'package:angular2/common.dart#COMMON_DIRECTIVES'
    platform_pipes:
    - 'package:angular2/common.dart#COMMON_PIPES'
- dart_to_js_script_rewriter
